Repository dwisiswant0/apkleaks, pull requests merged in 2021-03, with the labels that each got.

#28 Preparing v2.0.6
  .github/SECURITY.md
  .github/workflows/codeql.yaml
  .gitignore
  README.md
  VERSION
  apkleaks.py
  apkleaks/apkleaks.py
Labels: bug, documentation, enhancement

#31 Remove unnecessary dependency & decompile the entire APK
  apkleaks/apkleaks.py
  requirements.txt
Labels: enhancement

#36 Prep v2.3.0
  MANIFEST.in
  README.md
  VERSION
  apkleaks/apkleaks.py
  apkleaks/cli.py
  config/regexes.json
  setup.py
Labels: documentation, enhancement

#39 fix docker run command in README.md
  README.md
Labels: documentation

#41 Hotfix unclosed file output
  apkleaks/apkleaks.py
Labels: bug
